[package]
name = "hellfire-jit"
version = "0.1.0"
edition = "2021"

[dependencies]
#llama = "0.9.0"
# A version with a fix applied for transforms
llama = { "git" = "https://github.com/MinusGix/llama" }
